README.md
alb/main.tf
alb/outputs.tf
alb/variables.tf
s3/main.tf

- ALB module added
- Load balancer access logging to S3 bucket
- Update SSL policy to enable perfect forward secrecy

ALB module

---

alb/main.tf
alb/outputs.tf
alb/variables.tf

Add extra options to the ALB module to cater for Keycloak, Consignment API and frontend app

ALB module updates

---

README.md
config/variables.tf
route53/main.tf
route53/variables.tf
securityhub/data.tf
securityhub/main.tf
ses/main.tf
ses/variables.tf

- Enable Security Hub in London region with CIS benchmark standard
- Move conditional statement for DNS delegation from modules
- Move conditional statement for manual creation of hosted zones from modules

Security Hub

---

alb/main.tf
s3/main.tf

Just a couple of changes to get the terraform apply for the new environments working

Changes for staging deploy

---

lambda/locals.tf
lambda/templates/av_lambda.json.tpl
lambda/variables.tf
lambda/yara_av.tf

The environment variable was pointing to the dead letter queue but it is supposed to be pointing to the queue which does the updates to the api. I've updated this.
I've also added permissions to access this queue and I've sneaked in a change to remove the lambda from the vpc as it doesn't need to be there.

Update lambda env var sqs queue

---

s3/locals.tf
s3/main.tf
s3/outputs.tf

log sns topic handled by different set of variables and locals
Removing to make clearer

Removed unnecessary creation of log topic arn

---

Jenkinsfile-check

Requires PR: https://github.com/nationalarchives/tdr-jenkinslib/pull/34

Jenkins build to check Terraform formatting

---

ssm_maintenance_window/main.tf
ssm_maintenance_window/variables.tf

Just noticed that this resource can be tagged.

Add common tags to maintenance window module

---

ses/main.tf

This doesn't need to be in the SES configuration for intg/staging as
we're sending to that address and we're sending it from the management
account anyway.

Remove the notifications email resource

---

ec2/templates/user_data_postgres.sh.tpl
lambda/create_db_users.tf
lambda/locals.tf
lambda/variables.tf

- Add parameters to allow us to reuse the existing module
- Remove create user from user_data script

Add bastion user lambda

---

lambda/api_update.tf
lambda/checksum.tf

The others have already been done.

Upgrade lambdas to java11

---

lambda/notifications.tf

Requires PR: https://github.com/nationalarchives/tdr-configurations/pull/112

Muted ECR alerts still needed

---

iam_policy/templates/keycloak_ecs_task_role_policy.json.tpl
rds/main.tf
rds/outputs.tf
rds/variables.tf

I've added a variable to set IAM authentication on the datbase with a
default of true. Keycloak is the only thing using this module so that's
OK.
The other changes is to allow the ECS task policy to get the IAM
password for that user.

RDS changes for Keycloak.

---

lambda/notifications.tf

* The original slack webhook is now called SLACK_TDR_WEBHOOK
* The new #da-tdr-notifications webhook is now SLACK_WEBHOOK
This means that we can deploy this without breaking the notifications.
If it gets confusing, we can change it.

Add new slack webhook.

---

iam_policy/templates/keycloak_ecs_task_role_policy.json.tpl
rds_instance/main.tf
rds_instance/outputs.tf
rds_instance/variables.tf

- Add a module for an rds instance.
- Update ECS task role
- Make it multi-az for prod

TDR 2222 single db instance

---

lambda/notifications.tf
lambda/templates/notifications_transform_engine_lambda.json.tpl
lambda/variables.tf

Added SSM parameters for sns topic-in, standard bucket and KMS keys
Give permission for lambda to send SNS messages using the created kms key

Tdr 2391 TDR to TRE notifications variables

---

waf/main.tf
waf/variables.tf

This will send the waf logs to the provided cloudwatch arn

Add waf logging configuration.

---

iam/main.tf
iam/templates/iam_user_manage_credentials.json.tpl
iam/variables.tf

Need permissions so can set up MFA for individual IAM users

Security audit users need to manage credentials

---

rds_instance/main.tf
rds_instance/variables.tf

This allows me to change it to 30 for Keycloak ones without breaking
anything that expects it to be hard coded as 7.

TDR-2962 Add variable for backup retention period.

---

stepfunctions/main.tf

Permissions added in this PR: https://github.com/nationalarchives/tdr-terraform-environments/pull/331

Enable x-ray logging for step functions

---

cloudwatch_logs/main.tf
cloudwatch_logs/variables.tf

Adds the `retention_in_days` variable for creating log groups

TDR-3246 Log group Retention

---

rds_instance/main.tf
rds_instance/variables.tf

Need to add version as variable to ensure any upgrades are controlled

DB instances running different versions following auto-upgrade

---

lambda/service_unavailable.tf

Tested locally and it's working fine with python3.9

Upgrade python to 3.9 for service_unavailable lambda

---

rds_instance/main.tf
rds_instance/variables.tf

The tdr-terraform-environment will also need updating

TDR-3505 Update RDS instance certificate

---

api_gateway_account/main.tf
api_gateway_account/templates/api_cloudwatch_policy.json.tpl
cloudtrail/locals.tf
cloudtrail/main.tf
cloudtrail/templates/cloudwatch_logs_policy.json.tpl
config/main.tf
iam_policy/templates/consignment_export_task_policy.json.tpl
lambda/templates/create_db_users_lambda.json.tpl
lambda/templates/create_keycloak_users_api_lambda.json.tpl
lambda/templates/create_keycloak_users_s3_lambda.json.tpl
lambda/templates/export_authoriser_policy.json.tpl
lambda/templates/export_status_update_policy.json.tpl
lambda/templates/reporting_policy.json.tpl
lambda/templates/rotate_keycloak_secrets_policy.json.tpl
lambda/templates/service_unavailable.json.tpl
lambda/templates/signed_cookies_policy.json.tpl

This reverts commit f2acf4d9bdbe2c99f033480eb7ef7530069d3b3a.

Revert "TDRD-22 - Add "condition" to the trust polices"

---

s3/main.tf
s3/variables.tf

Buckets will require additional lifecycle configuration rules to manage objects within TDR

Dynamic lifecycle config rules

---

s3/locals.tf
s3/main.tf
s3/variables.tf

Set different tags for s3 bucket and its associated logs bucket
Supports AWS Backup set up

S3 setting of tags independently

---

lambda/data.tf
lambda/ecr_scan.tf
lambda/notifications.tf

Tdrd 845/lambda module org condition

---

ec2/main.tf
ec2/templates/ec2_assume_role.json.tpl

fix: Add trust condition for trust policy

---

lambda/create_db_users.tf
lambda/create_keycloak_users_api.tf
lambda/create_keycloak_users_s3.tf
lambda/export_api_authoriser.tf
lambda/export_status_update.tf
lambda/log_data.tf
lambda/reporting.tf
lambda/rotate_keycloak_secrets.tf
lambda/service_unavailable.tf
lambda/signed_cookies.tf

The test of the lambda roles used in the environments.  Tested in INT

fix: Use policy with trust condition for role trust policy

---

generic_lambda/main.tf
generic_lambda/templates/lambda_assume_role.json.tpl

Fixes eight roles.  Works int INT

fix: Add Trust policy condition for role

---

cloudtrail/data.tf
cloudtrail/main.tf
cloudtrail/templates/assume_role_policy.json.tpl

feat: Fix confused deputy for cloudwatch assume role policy

---

cloudtrail/main.tf
cloudtrail/variables.tf

Retention period for cloudwatch log group for cloudtrail
This was rebased from TDRD-845/cloudtrail_cloudwatch_trust_policy_confused_deputy
So please approve that first branch PR first
https://github.com/nationalarchives/tdr-terraform-modules/pull/332

chore: Add param for log group retention
