- config/templates/s3_access_policy.json.tpl
- route53/main.tf
- ses/main.tf
Allows Jenkins pipeline to run without errors before, and after, DNS delegation of a newly created hosted zone is in place
> DNS delegation of hosted zone

- s3/main.tf
- s3/variables.tf
Buckets that are accessed from the browser need cors configuration. For
now, I've set the allowed hosts to be the frontend only which will
probably be all we need but we can change it later if needs be.
> Add optional cors config to the bucket.

- alb/main.tf
- alb/variables.tf
Allow clients to set the number of health checks which need to fail before an application is considered unhealthy.
This will let us raise the threshold for Jenkins, which is sometimes down for a few minutes while restarting. In that case, it's better to wait to see whether it starts up again before deploying a new ECS container.
> Make the ALB health check unhealthy threshold configurable

- sqs/data.tf
- sqs/main.tf
- sqs/templates/default_policy.json.tpl
- sqs/templates/sns_topic_policy.json.tpl
- sqs/variables.tf
SQS queues require policy to provide permissions to perform actions on the SQS queue
Default policy provides general permissions
SNS Topics policy provides specific permissions for SNS topics
> Add polices for SQS queues

- lambda/log_data.tf
- s3/main.tf
- s3/variables.tf
Update the parameters for the S3 module so that multiple frontend origins can be passed in a parameter.
This will allow us to configure integration so that files can be uploaded from the local dev environment as well as from the integration frontend, which makes it possible to do local dev against a real integration S3 bucket.
If no origins are passed, do not enable CORS at all.
Also fix a Terraform syntax warning.
> Allow multiple CORS origins to upload to an S3 bucket

- lambda/api_update_av.tf
- lambda/variables.tf
Allows terraform to run without errors in environments like mgmt where this SSM parameter doesn't exist
> Fix SSM parameter issue in mgmt

- lambda/api_update_av.tf
- lambda/functions/log-data/lambda_function.py
- lambda/templates/log_data.json.tpl
Ensures the ACL of an object copied from one AWS account to another is transferred to the AWS account of the target bucket.
Removes a data lookup for an SSM parameter which is no longer required and causes an error in mgmt
> Permissions for copying S3 objects across accounts

- lambda/checksum.tf
- lambda/yara_av.tf
The checksum lambda processed a 3Gb file in just over two minutes so 3
seems like a reasonable compromise at this point.
I've increased the lambda to the same although it doesn't usually
appear to take this long. It keeps things consistent anyway and most
errors we get are memory or the code throwing exceptions so the number
of hanging lambdas should be negligable.
> Increased the timeouts for the lambdas.

- efs/locals.tf
- efs/outputs.tf
- efs/templates/backend_checks_access_policy.json.tpl
- lambda/download_files.tf
- lambda/file_format.tf
- lambda/variables.tf
EFS file system to be used by all backend checks initially named for file format check only
Rename resources to reflect use by all backend checks
> Rename efs file system for backend checks

- ses/main.tf
SES has been set up so that we need to add any addresses we want to send emails to. I imagine this can be configured somewhere but for now this is fine so I've added in the tdr_management address so we can send ECR scan notifications to that address.
> Add tdr management email

- ecr/main.tf
- ecr/templates/expire_untagged_images.json.tpl
When we push an image to ecr with a tag which is already assigned to an
image, intg or latest or whichever, the original image is kept in an
untagged state.
There's no reason for us to keep these. They don't affect our rollback
process at all so they're just taking up space.
This rule will delete them once the image is over a day old.
> Add a lifecycle policy to remove untagged images.

- ssm_maintenance_window/data.tf
- ssm_maintenance_window/main.tf
- ssm_maintenance_window/variables.tf
This forces the module to wait for the EC2 instance to be created, which means the maintenance task is run on the latest version of the instance.
This fixes a bug where the EC2 instance was updated, but Terraform couldn't tell that the instance ID needed to be updated to match.
> Pass EC2 instance ID instead of name to maintenance window module

- alb/outputs.tf
This is used by the frontend module to get the network interface IPs.
> Output the alb id

- s3/main.tf
- s3/variables.tf
It's possible that we have multipart uploads which are partially completed, either because it's timed out, or the connection died or they closed the browser. This rule will delete anything that's older than 7 days. Documentation is here.
https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html#mpu-stop-incomplete-mpu-lifecycle-config
> Add lifecycle rule to delete aborted uploads

- ecr/variables.tf
All of the existing ECR repos pass this parameter, so the default is no longer needed. Removing the default means that we won't forget to add the tag when we create new ECR repos.
> Remove default ECR image source parameter

- lambda/notifications.tf
- lambda/variables.tf
- sns/data.tf
- sns/main.tf
- sns/templates/notifications.json.tpl
- stepfunctions/main.tf
- stepfunctions/templates/consignment_export_definition.json.tpl
- stepfunctions/templates/consignment_export_policy.json.tpl
- stepfunctions/variables.tf
This has been set up so the step functions for the export can send notifications using the lambda in the management account but it can be used for anything that needs to send notifications from intg, staging or prod. If a message is sent to the sns topic tdr-notifications-$stage, it will trigger a notification.
There are notification lambda changes to add permissions for the sns queues to invoke the notification lambda.
There are changes to the sns topics to add a permission which allows the management account to subscribe to them.
Lastly, there are changes to the export step function to send a message to the sns topic on failure or success and a permission change to allow it to send those messages.
> Changes to allow notifications from other accounts

- stepfunctions/main.tf
- stepfunctions/templates/consignment_export_definition.json.tpl
The environment will be passed to the notification lambda which will use it in the slack message it sends.
> Add the environment to the notification step.

- s3/main.tf
- s3/variables.tf
Every S3 bucket is created using this module so removing it from here
will remove it from all buckets which had the version_lifecycle variable
set to true.
> Remove version expiration

- ecr/templates/auth_server_policy.json.tpl
- ecr/templates/consignment_api_policy.json.tpl
- ecr/templates/consignment_export_policy.json.tpl
- ecr/templates/file_format_policy.json.tpl
- ecr/templates/transfer_frontend_policy.json.tpl
The roles in these ECR access policies need to exist otherwise terraforn will fail. We took prod down so these need to come out for a bit.
> Remove prod policies

- lambda/notifications.tf
- lambda/variables.tf
Set an environment variable containing the provided list of muted vulnerability names. These are CVEs for which no fix is available, and which should be temporarily muted in the email and Slack alerts.
> Add list of muted ECR alerts to notifications lambda

- lambda/api_update.tf
- lambda/checksum.tf
- lambda/create_db_users.tf
- lambda/download_files.tf
- lambda/ecr_scan.tf
- lambda/export_api_authoriser.tf
- lambda/file_format.tf
- lambda/log_data.tf
- lambda/notifications.tf
- lambda/yara_av.tf
- Encrypt the lambda av variables - I missed this one off the original PR.
- Set environment to ignore - If you don't, terraform will report a change every time you run it as
each call to kms to encrypt the variables gives a slightly different
encrypted text and I can't find any way around it other than to ignore
the environment variables.
> Encrypt AV variables

- lambda/export_api_authoriser.tf
The export api authoriser lambda is taking longer than 10 seconds since
we added the encrypted environment variables.
It's possible that this is caused by a high cpu load when it's
decrypting and as memory in lambda is linked to cpu, increasing the
memory should increase the cpu and speed it up a bit.
> Increase authoriser memory

- lambda/create_db_users.tf
- lambda/create_keycloak_db_user.tf
- lambda/locals.tf
- lambda/outputs.tf
- lambda/templates/create_keycloak_db_user_lambda.json.tpl
- lambda/variables.tf
I've added a new lambda to create the keycloak database user. This goes into the keycloak VPC.
There's a PR here to update the create-db-users code to create the keycloak user as well https://github.com/nationalarchives/tdr-create-db-users/pull/4
I've also added in a DATABASE_NAME environment variable to the existing create-db-users lambda as this is how the lambda determines which users to create.
> Add create keycloak user lambda

- kms/variables.tf
Make the default policy the one that grants access to the root
account: https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html#key-policy-default-allow-root-enable-iam
tdr-terraform-environments needs to use a non-default policy, but it has already been switched to a specific policy in https://github.com/nationalarchives/tdr-terraform-environments/pull/133
Marking this as a draft PR until that environments PR has been merged.
> Switch default KMS policy to root-only access

- ec2/templates/user_data_postgres.sh.tpl
Some of the newer tables are created by the migrations user which the admin user doesn't have permission to grant read rights to.
We need to switch to the miagrations_user role and grant select permissions on all tables to the bastion user can see them.
> Switch user to migrations_user and grant permissions.

- ses/data.tf
- ses/locals.tf
- ses/main.tf
- ses/variables.tf
This reverts commit 423c6c4665893360b2488b8b479bccb06d229659.
Fetching the default email address from the parameter store only worked in the mgmt account. In other environments, the parameter didn't exist, so any script that depended on the SES module failed.
> Revert "Use system param to get email for ses module."

- ecs/templates/grafana_build.json.tpl
Setting the protocol to https requires a certificate
Difficult to run ECS task on https
Adding redirect rules as alternative
> Reset Grafana server protocol to http

- ec2/main.tf
- waf/main.tf
I added these while I was building Jenkins to prevent the AMI being
built and to add in the manual IP address for the pen testers. I
shouldn't have committed it so I'm reverting the changes here.
> Remove temporary changes.

- iam_policy/templates/jenkins_fargate_integration.json.tpl
This stops the integration Jenkins deploying Grafana terraform or the notifications lambdas or anything else that's deployed to the management account.
> Remove permissions for integration to deploy to management.

- alb/main.tf
This is from the pen test where they advised we should have deletion
protection on the load balancer.
As everything is using the terraform-modules, this change will apply to
all the load balancers.
> TDR-1146 TDR-1147 Enable deletion protection and drop invalid headers on ALB

- sqs/templates/failure_queue_policy.json.tpl
- sqs/templates/file_checks_policy.json.tpl
From the pen test, we had a low priority finding to say that the access
policies for the queues were too permissive. I've updated the the three
file check queues to only allow the download files role to send messages
to it and I've updated the failure queue to only allow the specific
other queues to call it.
> Add two file check queue policies.

- ecs/grafana_build.tf
- ecs/templates/grafana_build.json.tpl
Grafana defaults to the root url to a construction of protocol, domain and port
Change this to protocol and domain, as having port causes broken links in Alerts
> Explicitly state root url

- cloudtrail/main.tf
- cloudtrail/variables.tf
Later versions of Terraform require the log stream wildcard ':*' to be explicitly stated for the 'cloud_watch_logs_group_arn'
To support upgrade of Terraform allow log stream wildcard to be passed as a variable where the calling module has been upgraded
Default to empty string to continue support of non-upgrade modules
> Log stream wildcard variable

- iam_policy/templates/restored_db_access.json.tpl
If we have to create a new database from a snapshot for the API, the task role for the API will need a policy attaching which will allow it to connect to the new cluster. This is called in the tdr-scripts project but the policy definition is here.
> Add policy to attach to the api ECS service.

- iam_policy/templates/jenkins_fargate_integration.json.tpl
- iam_policy/templates/jenkins_fargate_prod.json.tpl
There is a role in the sub accounts that is used to describe ec2
instances so we can determine if the bastion needs to be deleted. This
allows Jenkins to pass the role.
> Add permissons for the fargate role to assume describe instance role

- iam_policy/templates/jenkins_ecs_task.json.tpl
We're adding a slack webhook for the release channel but the permission was missing to get the parameter from the parameter store.
> Add permission for new slack webhook.

- lambda/checksum.tf
- lambda/create_db_users.tf
- lambda/create_keycloak_db_user.tf
- lambda/download_files.tf
- lambda/ecr_scan.tf
- lambda/notifications.tf
- lambda/variables.tf
- lambda/yara_av.tf
This will allow tdr-terraform-environments to set the value, and use it to determine other values like the corresponding SQS message visibility timeout.
Set the default to 180 seconds, because this is a common value that many of the non-file-check Lambdas use.
For now, keep the hard-coded values for Lambdas which do not use the default values. Once tdr-terraform-frontend has been updated to pass in this parameter, there will be another PR to use the parameter for all Lambdas.
> Make lambda timeout configurable

- lambda/api_update.tf
- lambda/export_api_authoriser.tf
- lambda/file_format.tf
- lambda/log_data.tf
All of the Terraform repos have been updated to pass this parameter if the value is not the default, so replace all the hard-coded values with the parameter.
Marking as draft until https://github.com/nationalarchives/tdr-aws-accounts/pull/33 is merged.
> Update all lambdas to use timeout parameter

- lambda/api_update.tf
- lambda/checksum.tf
- lambda/create_db_users.tf
- lambda/create_keycloak_db_user.tf
- lambda/download_files.tf
- lambda/ecr_scan.tf
- lambda/export_api_authoriser.tf
- lambda/file_format.tf
- lambda/log_data.tf
- lambda/notifications.tf
- lambda/service_unavailable.tf
- lambda/variables.tf
- lambda/yara_av.tf
As part of the work we're doing to try and reduce load on the API to
allow for larger transfers, we want to restrict the number of concurrent
download files lambdas we have which restricts the number of concurrent
file check lambdas running which reduces the load on the API.
I've added in the variable and added the new parameter to the download
files lambda.
> Add reserved concurrency variable and set for download files lambda

- ecs/templates/consignment_export_task_policy.json.tpl
We're trying to send the task heartbeat to the step function to prevent
exports getting stuck but the task role was missing the permission to
allow it to do this.
> Add SendTaskHeartbeat permission.

- ecr/templates/auth_server_policy.json.tpl
As part of moving Keycloak to the TDR VPC, I renamed the roles to match
the pascal case naming of the newer ones. This has all been moved over
so these roles no longer exist.
> Remove old iam roles from auth ecr policy.

- s3/main.tf
- s3/variables.tf
The S3 buckets can only have canned ACLs at the moment https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl
We need to allow full control for the logs delivery account described https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#AccessLogsBucketAndFileOwnership
This allows Cloudfront to log requests made to S3.
There is a separate change in terraform-environments to set the new variable
> Allow custom ACL grants for S3 buckets.

- iam_policy/templates/jenkins_av_lambda.json.tpl
The rule update job needs access to backend-code-mgmt to get the
existing rules file in order to compare them and the
antivirus-test-files for the test files.
> Add policy for AV update checks.

- iam_policy/templates/jenkins_av_lambda.json.tpl
We need the ListBucket permission so the Jenkins job can download the
test files.
> Add missing ListBucket permission.

- waf/main.tf
I originally did this because I thought it would help running the e2e tests in parallel. It didn't but I've done it now and there was a note from Paul to say we should do this when terraform supports it which it does now.
> Upgrade to WAF V2

- waf/main.tf
This allows the GitHub actions runners to access the front end so it can
run the e2e tests.
> Add US to the allowed countries for intg and staging

- github_environments/main.tf
- github_environments/variables.tf
At the moment, we have to approve each one of the parallel jobs because
of the protection rules on the staging and prod environments. This
doesn't make sense for the e2e tests so I've added in an option to not
set a team slug which won't add protection rules.
> Make team slug optional.

- rds/variables.tf
AWS has been upgrading the RDS databases in the background and now the
versions are out of sync with terraform.
This now matches the deployed version.
> Upgrade databases

- github_environments/main.tf
The way this was didn't originally work, if we added any approvers to
integration, it was adding the admin team which is not that helpful.
This should work to allow us to use the transfer-digital-records team as
approvers.
> Use the correct team for integration.

- s3/templates/cloudfront_oai.json.tpl
This allows the Cloudfront OAI to tag the objects.
> Add PutObjectTagging.

- lambda/templates/av_lambda.json.tpl
The AV lambda needs to copy files from the dirty to the clean bucket.
These files are now tagged so the AV lambda needs these permissions to
get the tags from the dirty bucket and put them back on the clean
bucket.
> Add ObjectTagging permissions.

- lambda/notifications.tf
This key was originally defined in the Jenkins project but this has been
deleted.
I've moved the key definition into terraform-backend which will then
pass the arn to this lambda as a variable.
> Use KMS key from variable.

- lambda/notifications.tf
No ECR scan alerts that need muting.
Remove the environment variable from the notifications lambda, as cannot encrypt an empty value
> Remove muted ECR scan alerts

- lambda/data.tf
Value should be 'sbox'
This is causing the tdr-aws-account terraform to fail when run against the AWS sandbox environment
> Incorrect name used for the 'sandbox' environment

- lambda/reporting.tf
It's the reporting secret that this needs not the backend checks secret.
It doesn't really matter but it's nice to be consistent.
> Change incorrect variable name.

- lambda/rotate_keycloak_secrets.tf
The cloudwatch event hasn't been created because I used the wrong
variable.
> Use the correct count variable.

- cloudfront/outputs.tf
- kms/templates/message_system_access.json.tpl
- shield/main.tf
- shield/variables.tf
- waf/main.tf
- Add cloudfront arn to outputs.
- Add cloudwatch to the KMS policy to allow cloudwatch rules to be sent to the notifications topic.
- Add a rate-based-rule.
- Add shield protection module
> TDR 1829 changes for advanced shield

- lambda/file_format.tf
- lambda/variables.tf
These will be used by the updated lambda. By adding them alongside the
existing variables, we can deploy without down time and remove the old
ones afterwards.
> Add new variables to file format lambda.

- lambda/notifications.tf
I have added a new webhook on aws parameter store called `/intg/slack/export/webhook` the same will need to be done for Staging and Production but I do not have permission to do that.
> Add webhook for new da-tdr-export-notifications channel

- ssm_parameter/main.tf
This will allow a SSM parameter to be added to a tier other than the default 'Standard' tier
> Add 'tier' as optional field

- waf/main.tf
The problem is that some of the GitHub action IPs look like they're coming from Germany which is not on our allowed list of countries so it's returning 403. I've added Germany in to the allowed list and the tests are passing
> Add DE to allowed regions

- stepfunctions/templates/consignment_export_definition.json.tpl
The timeout was set to 10 minutes and the 10largefiles export (Around
5.5Gb) was taking around 15 minutes.
This should allow us a roughly 10Gb total export before we have to change it
again.
> Increase timeout for export

- waf/main.tf
There are two problems here. The first is that requests from users who
are uploading 10000 files are hitting the rate limit and they're getting
forbidden from the front end when we try to make an API call.
The second problem is that the backend checks are hitting the rate limit
when they try to call the API.
The limit increase is to stop users seeing 403 errors and the
scope_down_statement stops the rate limiting rule counting IPs in the
trusted IP set, which includes the NAT gateway IPs so this should stop
the backend checks counting towards the limit.
This isn't foolproof, it works off the IP in the header which can be
spoofed but it should stop most obvious DDOS attempts.
> Increase WAF rate limits.

- kms/templates/cloudwatch.json.tpl
Event bridge is sending messages to the notification SNS topic in the
management account and that topic is encrypted at rest so event bridge
needs permission to decrypt with this KMS key.
> Add event bridge permissions.

- sqs/templates/transform_engine_retry_policy.json.tpl
- sqs/templates/transform_engine_v2_retry_policy.json.tpl
There is a statement in this policy which allows TRE to send messages to
this queue but the other statement isn't needed. SQS queues are owned by
default by the account so it should be able to invoke the notifications
lambda without this.
I've tested it and it will still invoke the lambda.
I'll mark this as draft while I check that TRE can still send messages.
> Remove the default_statement

- route53/locals.tf
- route53/main.tf
- route53/outputs.tf
The module wasn't working when create_hosted_zone was set to false
because it was seting variables as empty string. I've put in a data
block which finds the existing hosted zone and use that for the outputs
and this is working for tdr-aws-accounts. It might have broken something
else.
> Update route53 module.

- lambda/notifications.tf
The subscription to the TRE v2 SQS queue was causing a continuous loop due
The TRE v2 architecture will be removed anyway
> Remove notification lambda SQS subscription

- lambda/signed_cookies.tf
- lambda/variables.tf
There will be instances where the user session timeout may need to be adjusted temporarily on a per environment basis. For example to accommodate a large consignment
Have the user session timeout as an environmental variable for the signed cookies lambda so the cookie timeout matches the session timeout
> Make user session timeout configurable

- lambda/notifications.tf
Set `SLACK_STANDARD_WEBHOOK` environment variable so it can send the standard prod export notifications to the dedicated Slack channel
> TDRD-156 - Send standard prod export notifications to dedicated Slack channel

- lambda/notifications.tf
Added the following environment variables:
`METADATA_REVIEW_REQUESTED_TB_TEMPLATE_ID` -> Template that is sent to Transferring body user when metadata review requested
`METADATA_REVIEW_REQUESTED_DTA_TEMPLATE_ID`-> Template that is sent to DTA reviewer when user requests metadata review
`METADATA_REVIEW_REJECTED_TEMPLATE_ID` -> Template sent to TB user when metadata is rejected
`METADATA_REVIEW_APPROVED_TEMPLATE_ID`-> Template sent to TB user when metadata is approved
> TDRD-302/303 - Add new env variable for metadata review templates

- lambda/notifications.tf
We have exceeded the 4kb limit for the notifications environment variable lambda. These have now been moved to the notifications code.
Also added new ENVIRONMENT variable needed to differentiate between the environments
> Remove the templateId from the notifications environment variable

- certificatemanager/versions.tf
- lambda/log_data.tf
- s3/main.tf
- s3/templates/alb_logging_euwest2.json.tpl
- s3/templates/cloudfront_origin.json.tpl
- s3/templates/cloudtrail.json.tpl
- s3/templates/export_bucket.json.tpl
- s3/templates/lambda_update.json.tpl
- s3/templates/log-data.json.tpl
- s3/templates/secure_transport.json.tpl
- ssm_parameter/main.tf
**certificatemanager**  If passing providers the sub module should declare the aws provide with required_providers - warning default used otherwise. Needed tp pass different region provider as certificates are not eu-west-2. Providers can only be created in root
**lambda** in an aws_lambda_function the lifecycle block with ignore_changes for last_modified is no longer necessary in Terraform when using the aws_lambda_function resource because last_modified is now read-only and automatically managed by AWS.
If the purpose of ignoring last_modified was to avoid Terraform noticing changes unrelated to your Lambda function deployment, you no longer need to do anything. The last_modified attribute is informational and will not trigger updates or conflicts in recent versions of the AWS provider. …
> Tdrd 607 fix terraform warnings

- s3/main.tf
- s3/templates/secure_transport.json.tpl
- s3/templates/upload_cloudfront_logs.json.tpl
- s3/variables.tf
The bucket policy was being set from the canonical user id. AWS converts the principal to an AWS account id so every time a plan was made it would think changes needed to be made. If use Account Id directly in terraform this should be resolved
> Fix terrform warnings plan fix

- waf/main.tf
- waf/outputs.tf
- waf/variables.tf
Create a new IPSet for blocked IPs, this will not be removed but can be empty (deletions whilst in use causes terraform problems)
The rule to delete will be added directly to the acl (no need to use rule_group). The rule will only be added if there are IPs to block as rule incur a cost.
Priorities need to change so blocking will happen even if an IP had been previously added to whitelist)
> Tdrd 339 automated or semi automated workflow for blocking i ps with malicious activity

- s3/variables.tf
Adding before needed to avoid breaking changes
> S3 variable to support AWS backups

- kms/templates/message_system_access.json.tpl
AWS backup roles will only exist in prod
Therefore Terraform apply will fail in other environments
Need to change to dyanmic policy instead
> Policy will only work if roles exists
